### ISSUE TITLE
stream.pipe is not a function

### ISSUE THREAD

**Issue by thiagomajesk** [inuscript/gulp-unzip#27]
Hi! I'm trying to use this package with [gulp-download-stream](https://github.com/michalc/gulp-download-stream) and I'm receiving the following error:

```
TypeError: stream.pipe is not a function
    at DestroyableTransform.transform [as _transform] ({project-path}\node_modules\gulp-unzip\index.js:28:12)
    at DestroyableTransform.Transform._read ({project-path}\node_modules\readable-stream\lib\_stream_transform.js:177:10)
    at DestroyableTransform.Transform._write ({project-path}\node_modules\readable-stream\lib\_stream_transform.js:164:83)
    at doWrite ({project-path}\node_modules\readable-stream\lib\_stream_writable.js:405:139)
    at writeOrBuffer ({project-path}\node_modules\readable-stream\lib\_stream_writable.js:394:5)
    at DestroyableTransform.Writable.write ({project-path}\node_modules\readable-stream\lib\_stream_writable.js:303:11)
    at Readable.ondata (_stream_readable.js:746:22)
    at Readable.emit (events.js:210:5)
    at Readable.EventEmitter.emit (domain.js:540:23)
    at Readable.read (_stream_readable.js:546:10)
    at flow (_stream_readable.js:1015:34)
    at resume_ (_stream_readable.js:996:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

Is this related to the package or am I doing something wrong here?

**PS.:** It works fine with [gulp-download](https://github.com/Metrime/gulp-download) but It's much much slower since it's not parallel.

**Comment by UlisesGascon** [comment]
Hi @thiagomajesk! Can you share your gulpfile file or the task? Are you using Gulp 3.x or 4.x?

**Comment by thiagomajesk** [comment]
@UlisesGascon Yes, of course. I'm using Gulp 4.0.2 and this is the task:

```js
async function downloadIcons() {
    scrape((links) =>
        download(links)
            .pipe(unzip(unzipOptions))
            .pipe(svgo())
            .pipe(gulp.dest('static'))
    );
}
```

And this is the scrape function:

```js
module.exports.scrape = function (callback) {
    const baseTagsUrl = url.resolve(baseUrl, '/tags.html');
    scrapeIt(baseTagsUrl, options, (err, result) => {
        callback(err || result.data.links.map((o) => o.href));
    });
};
```

**Comment by thiagomajesk** [comment]
Hi, @UlisesGascon. First of all: Happy New Year! 🎊😄  
I've been minding to ask: Have you come across this issue recently and is there any extra information I could provide to help solve this?

**Comment by exocom** [comment]
@thiagomajesk I had the same issue, try using vinyl-buffer.
https://www.npmjs.com/package/vinyl-buffer

**Comment by guw** [comment]
Same problem with Gulp 5.

```JavaScript
download("https://..../foo.zip")
            .pipe(unzip())
            .pipe(gulp.dest('extracted'))
```

```
.../node_modules/gulp-unzip/index.js:28
    stream.pipe(unzip.Parse())
           ^

TypeError: stream.pipe is not a function
    at DestroyableTransform.transform [as _transform] (...node_modules/gulp-unzip/index.js:28:12)
    at Transform._read (...node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (...node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (...node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (...node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Writable.write (...node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at Readable.ondata (node:internal/streams/readable:1009:22)
    at Readable.emit (node:events:518:28)
    at Readable.emit (node:domain:552:15)
    at Readable.read (node:internal/streams/readable:782:10)
    at flow (node:internal/streams/readable:1283:53)
    at resume_ (node:internal/streams/readable:1262:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)

Node.js v22.11.0
```

For `download` I am using `"gulp-download2": "^1.1.0",`
